In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os 
import cv2


In [3]:
pip install opencv-python


Note: you may need to restart the kernel to use updated packages.


In [4]:
df = pd.read_csv('labels.csv')
print(df.tail())

                filepath  xmin  xmax  ymin  ymax
396  ./images\Cars95.xml   278   407   182   263
397  ./images\Cars96.xml   133   261   126   160
398  ./images\Cars97.xml    98   297   102   191
399  ./images\Cars98.xml    85   247   196   259
400  ./images\Cars99.xml    70   262   198   271


In [5]:
import xml.etree.ElementTree as xet

In [6]:
filename=df['filepath'][0]
filename

'./images\\Cars0.xml'

In [7]:
xet.parse(filename).getroot().find('filename').text

'Cars0.png'

In [8]:
def getfilename(filename):
    filename_image=xet.parse(filename).getroot().find('filename').text
    filepath_image=os.path.join('./images',filename_image)
    return filepath_image
getfilename(filename)

'./images\\Cars0.png'

In [9]:
image_path=list(df['filepath'].apply(getfilename))
image_path

['./images\\Cars0.png',
 './images\\Cars1.png',
 './images\\Cars10.png',
 './images\\Cars100.png',
 './images\\Cars101.png',
 './images\\Cars102.png',
 './images\\Cars103.png',
 './images\\Cars104.png',
 './images\\Cars105.png',
 './images\\Cars106.png',
 './images\\Cars107.png',
 './images\\Cars108.png',
 './images\\Cars109.png',
 './images\\Cars11.png',
 './images\\Cars110.png',
 './images\\Cars111.png',
 './images\\Cars112.png',
 './images\\Cars113.png',
 './images\\Cars114.png',
 './images\\Cars115.png',
 './images\\Cars116.png',
 './images\\Cars117.png',
 './images\\Cars118.png',
 './images\\Cars119.png',
 './images\\Cars12.png',
 './images\\Cars120.png',
 './images\\Cars121.png',
 './images\\Cars122.png',
 './images\\Cars123.png',
 './images\\Cars124.png',
 './images\\Cars125.png',
 './images\\Cars126.png',
 './images\\Cars127.png',
 './images\\Cars128.png',
 './images\\Cars129.png',
 './images\\Cars13.png',
 './images\\Cars130.png',
 './images\\Cars131.png',
 './images\\Cars132.

In [10]:
print(image_path[90])
file_path=image_path[90]
file_path

./images\Cars18.png


'./images\\Cars18.png'

In [11]:
img=cv2.imread(file_path)

cv2.namedWindow('example',cv2.WINDOW_NORMAL)
cv2.imshow('example',img)
cv2.waitKey(0)

cv2.destroyAllWindows()

In [12]:
cv2.rectangle(img,(313,286),(405,311),(0,255,0),3)

cv2.namedWindow('example',cv2.WINDOW_NORMAL)
cv2.imshow('example',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [16]:
#Data preprocessing
from sklearn.model_selection import train_test_split





In [17]:
from tensorflow.keras.preprocessing.image import load_img, img_to_array

In [18]:

labels=df.iloc[:,1:].values
labels

array([[226, 419, 125, 173],
       [134, 262, 128, 160],
       [140, 303,   5, 148],
       ...,
       [ 98, 297, 102, 191],
       [ 85, 247, 196, 259],
       [ 70, 262, 198, 271]], dtype=int64)

In [27]:
import numpy as np
import pandas as pd
data=[]
output=[]

for ind in range(len(image_path)):
    image=image_path[ind]
    img_arr=cv2.imread(image)

    h,w,d=img_arr.shape
    #preprocessing

    load_image=load_img(image,target_size=(224,224))
    load_image_arr=img_to_array(load_image)
    
    norm_load_image_arr=load_image_arr/225.0  #normalisation

    #normalisation to labels
    xmin,xmax,ymin,ymax=labels[ind]
    nxmin,nxmax=xmin/w,xmax/w
    nymin,nymax=ymin/h,ymax/h
    label_norm=(nxmin,nxmax,nymin,nymax)
    #--------append----
    data.append(norm_load_image_arr)
    output.append(label_norm)

#print data and output once

[[[ 73. 130. 159.]
  [ 44. 124. 159.]
  [ 80. 149. 182.]
  ...
  [ 42.  44.  41.]
  [ 41.  42.  44.]
  [ 33.  34.  36.]]

 [[ 65. 121. 146.]
  [ 41. 121. 156.]
  [ 50. 119. 150.]
  ...
  [ 44.  46.  45.]
  [ 40.  42.  41.]
  [ 41.  43.  42.]]

 [[ 65. 117. 139.]
  [ 40. 120. 153.]
  [ 56. 123. 152.]
  ...
  [ 45.  45.  47.]
  [ 49.  54.  50.]
  [ 35.  40.  36.]]

 ...

 [[ 73.  50.  42.]
  [ 73.  50.  42.]
  [ 73.  50.  42.]
  ...
  [100.  63.  44.]
  [102.  67.  47.]
  [103.  68.  48.]]

 [[ 76.  53.  45.]
  [ 74.  51.  43.]
  [ 72.  49.  41.]
  ...
  [ 99.  61.  42.]
  [103.  66.  47.]
  [104.  67.  48.]]

 [[ 75.  52.  44.]
  [ 72.  49.  41.]
  [ 70.  47.  39.]
  ...
  [102.  64.  45.]
  [102.  64.  45.]
  [103.  65.  46.]]]
[[[223. 243. 249.]
  [225. 244. 252.]
  [225. 244. 251.]
  ...
  [254. 255. 255.]
  [253. 255. 254.]
  [254. 255. 254.]]

 [[224. 243. 249.]
  [225. 244. 251.]
  [225. 244. 250.]
  ...
  [254. 255. 254.]
  [253. 255. 254.]
  [254. 255. 255.]]

 [[224. 244. 248.]

[[[  1.   3.   0.]
  [  1.   3.   0.]
  [  1.   3.   0.]
  ...
  [  6.   4.   5.]
  [  5.   5.   5.]
  [  4.   4.   4.]]

 [[  3.   3.   3.]
  [  3.   3.   3.]
  [  3.   3.   3.]
  ...
  [  8.   6.   7.]
  [  8.   6.   7.]
  [  7.   5.   6.]]

 [[  4.   4.   4.]
  [  3.   3.   3.]
  [  3.   3.   3.]
  ...
  [  8.   6.   7.]
  [  8.   6.   7.]
  [  8.   6.   7.]]

 ...

 [[ 97.  46.  15.]
  [ 89.  38.   7.]
  [ 99.  48.  17.]
  ...
  [ 20.  11.   6.]
  [ 17.  10.   2.]
  [ 26.  19.  11.]]

 [[ 95.  45.  12.]
  [ 91.  41.   8.]
  [ 98.  48.  15.]
  ...
  [ 21.  12.   7.]
  [ 16.   9.   1.]
  [ 23.  16.   8.]]

 [[ 92.  40.   3.]
  [102.  50.  13.]
  [ 99.  46.  12.]
  ...
  [ 19.  10.   5.]
  [ 19.  12.   4.]
  [ 20.  13.   5.]]]
[[[255. 255. 251.]
  [255. 255. 255.]
  [250. 254. 255.]
  ...
  [250. 254. 255.]
  [255. 254. 255.]
  [255. 252. 255.]]

 [[255. 255. 255.]
  [137. 137. 139.]
  [116. 114. 115.]
  ...
  [120. 128. 130.]
  [ 59.  60.  64.]
  [255. 253. 255.]]

 [[252. 255. 250.]

[[[251. 254. 242.]
  [255. 255. 251.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 [[254. 255. 249.]
  [255. 255. 252.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 [[253. 253. 251.]
  [255. 255. 253.]
  [255. 255. 253.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 ...

 [[130. 130. 136.]
  [105. 106. 111.]
  [112. 113. 116.]
  ...
  [151. 150. 157.]
  [130. 128. 139.]
  [131. 130. 140.]]

 [[136. 136. 144.]
  [116. 117. 122.]
  [124. 125. 128.]
  ...
  [141. 140. 149.]
  [130. 129. 140.]
  [127. 126. 136.]]

 [[113. 113. 122.]
  [128. 129. 134.]
  [138. 139. 142.]
  ...
  [111. 110. 120.]
  [138. 137. 149.]
  [110. 109. 117.]]]
[[[  1.   3.   0.]
  [  1.   3.   0.]
  [  1.   3.   0.]
  ...
  [  6.   4.   5.]
  [  5.   5.   5.]
  [  4.   4.   4.]]

 [[  3.   3.   3.]
  [  3.   3.   3.]
  [  3.   3.   3.]
  ...
  [  8.   6.   7.]
  [  8.   6.   7.]
  [  7.   5.   6.]]

 [[  4.   4.   4.]

[[[154. 102.  38.]
  [146. 106.  62.]
  [151. 127. 107.]
  ...
  [ 29.  32.  23.]
  [ 51.  41.  32.]
  [  6.   9.   4.]]

 [[164. 110.  41.]
  [155. 113.  64.]
  [169. 142. 119.]
  ...
  [ 22.  25.  17.]
  [ 58.  48.  37.]
  [ 13.  14.   8.]]

 [[147. 100.  46.]
  [163. 140. 121.]
  [173. 147. 121.]
  ...
  [ 17.  19.  15.]
  [ 52.  45.  35.]
  [ 23.  22.  14.]]

 ...

 [[144. 146. 148.]
  [150. 152. 152.]
  [151. 152. 153.]
  ...
  [170. 171. 171.]
  [168. 169. 169.]
  [148. 149. 149.]]

 [[144. 145. 147.]
  [151. 152. 154.]
  [149. 150. 152.]
  ...
  [169. 170. 171.]
  [179. 181. 181.]
  [158. 160. 160.]]

 [[145. 146. 147.]
  [147. 149. 150.]
  [153. 154. 155.]
  ...
  [161. 163. 163.]
  [171. 174. 174.]
  [165. 167. 167.]]]
[[[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 254. 230.]
  [255. 255. 232.]
  [255. 255. 230.]]

 [[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 254. 227.]
  [255. 255. 231.]
  [255. 255. 231.]]

 [[255. 255. 255.]

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 ...

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
[[[204. 184. 147.]
  [171. 150. 107.]
  [201. 180. 127.]
  ...
  [ 41.  40.  12.]
  [ 51.  47.  12.]
  [114. 105.  64.]]

 [[238. 224. 189.]
  [184. 168. 135.]
  [199. 180. 140.]
  ...
  [ 36.  36.  12.]
  [ 52.  48.  13.]
  [ 87.  78.  39.]]

 [[223. 219. 184.]
  [191. 180. 160.]
  [233. 217. 191.]
  ...
  [ 30.  29.   9.]
  [ 86.  81.  49.]
  [102.  92.  56.]]

 ...

 [[ 56.  31.   1.]
  [121.  97.  53.]
  [113.  94.  38.]
  ...
  [ 38.   8.   0.]
  [ 50.  22.  18.]
  [ 3

[[[220. 198. 180.]
  [220. 197. 179.]
  [188. 158. 150.]
  ...
  [240. 231. 253.]
  [239. 230. 253.]
  [239. 230. 253.]]

 [[220. 198. 179.]
  [219. 197. 178.]
  [206. 181. 168.]
  ...
  [240. 231. 253.]
  [239. 230. 254.]
  [239. 230. 254.]]

 [[217. 195. 177.]
  [215. 194. 175.]
  [205. 185. 168.]
  ...
  [240. 231. 254.]
  [240. 230. 253.]
  [239. 230. 253.]]

 ...

 [[ 25.  18.  17.]
  [ 25.  18.  17.]
  [ 26.  18.  18.]
  ...
  [  8.   9.   8.]
  [  8.   9.   8.]
  [  7.   9.   7.]]

 [[ 14.  13.  13.]
  [ 16.  13.  13.]
  [ 19.  13.  13.]
  ...
  [  6.   7.   5.]
  [  4.   6.   6.]
  [  7.   9.   9.]]

 [[ 10.  11.  11.]
  [  9.  11.  11.]
  [ 13.  10.   9.]
  ...
  [  8.   9.   7.]
  [  7.   9.   8.]
  [  9.  11.  11.]]]
[[[180. 188. 189.]
  [173. 182. 179.]
  [166. 170. 167.]
  ...
  [127. 129. 124.]
  [194. 197. 197.]
  [183. 189. 191.]]

 [[181. 188. 187.]
  [175. 182. 182.]
  [170. 179. 176.]
  ...
  [198. 206. 205.]
  [184. 191. 187.]
  [185. 194. 191.]]

 [[182. 188. 190.]

[[[ 60.  66.  20.]
  [ 78.  82.  45.]
  [ 62.  65.  34.]
  ...
  [ 54.  62.  47.]
  [ 45.  54.  37.]
  [ 45.  53.  38.]]

 [[ 63.  68.  28.]
  [ 68.  72.  35.]
  [ 47.  50.  19.]
  ...
  [ 37.  45.  30.]
  [ 33.  42.  25.]
  [ 33.  41.  26.]]

 [[ 63.  67.  34.]
  [ 69.  73.  36.]
  [ 38.  41.  10.]
  ...
  [ 43.  51.  36.]
  [ 34.  43.  26.]
  [ 34.  42.  27.]]

 ...

 [[191. 184. 176.]
  [200. 193. 185.]
  [188. 181. 173.]
  ...
  [ 82.  82.  82.]
  [ 96.  96.  96.]
  [ 85.  85.  85.]]

 [[191. 184. 174.]
  [182. 175. 165.]
  [195. 188. 178.]
  ...
  [ 98.  98.  98.]
  [ 95.  95.  95.]
  [ 97.  97.  97.]]

 [[156. 150. 138.]
  [147. 141. 129.]
  [198. 192. 180.]
  ...
  [ 79.  79.  79.]
  [100. 100. 100.]
  [ 76.  76.  76.]]]
[[[  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  ...
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]]

 [[  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  ...
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]]

 [[  0.   0.   0.]

[[[172. 180. 198.]
  [178. 186. 195.]
  [169. 180. 193.]
  ...
  [172. 184. 204.]
  [150. 157. 150.]
  [143. 141. 166.]]

 [[171. 179. 196.]
  [176. 184. 194.]
  [171. 182. 194.]
  ...
  [176. 185. 205.]
  [147. 154. 146.]
  [142. 142. 167.]]

 [[172. 183. 195.]
  [175. 183. 193.]
  [175. 185. 194.]
  ...
  [178. 186. 206.]
  [140. 147. 139.]
  [140. 140. 168.]]

 ...

 [[142. 142. 137.]
  [143. 143. 133.]
  [135. 137. 130.]
  ...
  [134. 137. 138.]
  [143. 145. 144.]
  [138. 142. 141.]]

 [[150. 152. 140.]
  [138. 139. 132.]
  [138. 139. 130.]
  ...
  [133. 137. 138.]
  [136. 139. 139.]
  [130. 133. 139.]]

 [[147. 149. 137.]
  [140. 140. 132.]
  [152. 154. 144.]
  ...
  [131. 135. 135.]
  [139. 140. 138.]
  [135. 139. 139.]]]
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 ...

[[[ 60.  66.  20.]
  [ 78.  82.  45.]
  [ 62.  65.  34.]
  ...
  [ 54.  62.  47.]
  [ 45.  54.  37.]
  [ 45.  53.  38.]]

 [[ 63.  68.  28.]
  [ 68.  72.  35.]
  [ 47.  50.  19.]
  ...
  [ 37.  45.  30.]
  [ 33.  42.  25.]
  [ 33.  41.  26.]]

 [[ 63.  67.  34.]
  [ 69.  73.  36.]
  [ 38.  41.  10.]
  ...
  [ 43.  51.  36.]
  [ 34.  43.  26.]
  [ 34.  42.  27.]]

 ...

 [[191. 184. 176.]
  [200. 193. 185.]
  [188. 181. 173.]
  ...
  [ 82.  82.  82.]
  [ 96.  96.  96.]
  [ 85.  85.  85.]]

 [[191. 184. 174.]
  [182. 175. 165.]
  [195. 188. 178.]
  ...
  [ 98.  98.  98.]
  [ 95.  95.  95.]
  [ 97.  97.  97.]]

 [[156. 150. 138.]
  [147. 141. 129.]
  [198. 192. 180.]
  ...
  [ 79.  79.  79.]
  [100. 100. 100.]
  [ 76.  76.  76.]]]
[[[171. 175. 110.]
  [164. 170.  94.]
  [147. 155.  68.]
  ...
  [114. 121.  64.]
  [102. 109.  53.]
  [102. 111.  48.]]

 [[171. 176. 104.]
  [159. 165.  86.]
  [143. 151.  64.]
  ...
  [119. 127.  69.]
  [110. 118.  61.]
  [101. 109.  47.]]

 [[152. 160.  75.]

[[[180. 179. 194.]
  [180. 180. 194.]
  [180. 179. 194.]
  ...
  [ 17.  23.  28.]
  [ 18.  24.  29.]
  [ 18.  24.  29.]]

 [[180. 179. 195.]
  [180. 180. 195.]
  [180. 179. 195.]
  ...
  [ 17.  23.  29.]
  [ 17.  23.  28.]
  [ 17.  23.  28.]]

 [[180. 179. 196.]
  [180. 179. 196.]
  [180. 179. 196.]
  ...
  [ 15.  21.  26.]
  [ 14.  20.  25.]
  [ 14.  20.  25.]]

 ...

 [[180. 180. 191.]
  [181. 180. 192.]
  [181. 179. 192.]
  ...
  [ 88.  85.  86.]
  [ 88.  85.  86.]
  [ 87.  83.  84.]]

 [[177. 179. 190.]
  [179. 179. 190.]
  [178. 175. 188.]
  ...
  [ 88.  85.  86.]
  [ 88.  85.  86.]
  [ 89.  86.  87.]]

 [[176. 178. 189.]
  [178. 178. 189.]
  [170. 167. 180.]
  ...
  [ 89.  86.  86.]
  [ 88.  85.  86.]
  [ 90.  86.  87.]]]
[[[112. 124.  94.]
  [ 27.  29.  23.]
  [ 20.  19.  20.]
  ...
  [133. 133. 122.]
  [136. 136. 125.]
  [134. 134. 123.]]

 [[ 42.  55.  29.]
  [ 15.  17.  10.]
  [ 26.  25.  24.]
  ...
  [136. 136. 125.]
  [137. 137. 126.]
  [135. 135. 124.]]

 [[ 36.  47.  28.]

[[[253. 255. 251.]
  [253. 255. 254.]
  [255. 255. 255.]
  ...
  [195. 228. 253.]
  [195. 228. 253.]
  [195. 228. 253.]]

 [[220. 229. 230.]
  [224. 233. 238.]
  [222. 231. 241.]
  ...
  [194. 226. 252.]
  [194. 226. 252.]
  [194. 226. 252.]]

 [[250. 255. 255.]
  [237. 244. 251.]
  [220. 230. 242.]
  ...
  [192. 225. 251.]
  [192. 225. 251.]
  [192. 225. 251.]]

 ...

 [[ 85.  93.  97.]
  [ 91.  98. 103.]
  [ 74.  81.  86.]
  ...
  [ 64.  64.  66.]
  [ 60.  61.  63.]
  [ 61.  62.  63.]]

 [[113. 122. 126.]
  [ 82.  89.  94.]
  [ 97. 104. 109.]
  ...
  [ 61.  62.  61.]
  [ 60.  62.  61.]
  [ 66.  68.  67.]]

 [[ 99. 108. 112.]
  [106. 113. 118.]
  [126. 134. 138.]
  ...
  [ 71.  72.  71.]
  [ 56.  57.  56.]
  [ 64.  65.  64.]]]
[[[182. 160. 137.]
  [182. 157. 131.]
  [168. 156. 148.]
  ...
  [223. 238. 196.]
  [241. 247. 209.]
  [220. 217. 182.]]

 [[174. 155. 137.]
  [179. 151. 126.]
  [179. 160. 143.]
  ...
  [169. 188. 129.]
  [235. 239. 191.]
  [177. 187. 147.]]

 [[166. 159. 154.]

[[[ 30.  29.  25.]
  [ 31.  30.  26.]
  [ 37.  36.  32.]
  ...
  [112. 104. 111.]
  [111. 102. 109.]
  [111. 102. 109.]]

 [[ 31.  30.  26.]
  [ 29.  28.  24.]
  [ 36.  35.  31.]
  ...
  [112. 104. 111.]
  [111. 102. 110.]
  [111. 103. 110.]]

 [[ 30.  29.  25.]
  [ 27.  26.  22.]
  [ 36.  36.  32.]
  ...
  [112. 104. 111.]
  [111. 102. 109.]
  [111. 103. 110.]]

 ...

 [[ 40.  35.  41.]
  [ 41.  35.  42.]
  [ 42.  37.  43.]
  ...
  [ 52.  44.  43.]
  [ 43.  37.  39.]
  [ 18.  13.  16.]]

 [[ 40.  34.  41.]
  [ 40.  35.  41.]
  [ 41.  36.  42.]
  ...
  [ 49.  43.  44.]
  [ 28.  23.  24.]
  [ 16.  11.  17.]]

 [[ 38.  32.  38.]
  [ 39.  33.  40.]
  [ 41.  35.  41.]
  ...
  [ 38.  36.  38.]
  [ 19.  15.  15.]
  [ 16.  12.  20.]]]
[[[242. 247. 251.]
  [168. 175. 183.]
  [147. 161. 172.]
  ...
  [101. 111. 120.]
  [ 89.  99. 108.]
  [ 94. 104. 113.]]

 [[249. 250. 252.]
  [230. 233. 238.]
  [188. 196. 206.]
  ...
  [ 99. 113. 124.]
  [ 83.  97. 108.]
  [ 88. 102. 113.]]

 [[251. 250. 248.]

[[[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 [[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 [[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 ...

 [[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 [[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 [[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]]
[[[ 77.  83.  51.]
  [121. 126.  97.]
  [149. 152. 134.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 [[ 84.  89.  58.]
  [117. 122.  93.]
  [147. 151. 132.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 [[178. 183. 155.]

[[[162. 178. 134.]
  [ 65.  68.  45.]
  [211. 216. 145.]
  ...
  [109. 130. 183.]
  [209. 220. 232.]
  [107. 110. 135.]]

 [[115. 127.  78.]
  [100. 116.  68.]
  [235. 234. 162.]
  ...
  [ 89.  94. 127.]
  [136. 143. 170.]
  [114. 118. 141.]]

 [[161. 177. 116.]
  [114. 124.  74.]
  [235. 230. 155.]
  ...
  [122. 131. 162.]
  [ 82.  84. 118.]
  [ 97.  99. 128.]]

 ...

 [[173. 167. 164.]
  [164. 156. 154.]
  [162. 154. 146.]
  ...
  [ 45.  41.  59.]
  [ 38.  34.  47.]
  [ 58.  58.  80.]]

 [[172. 164. 160.]
  [161. 153. 147.]
  [158. 148. 140.]
  ...
  [ 87.  95. 123.]
  [ 68.  62.  78.]
  [ 39.  34.  51.]]

 [[182. 175. 166.]
  [160. 151. 143.]
  [157. 148. 139.]
  ...
  [170. 199. 244.]
  [ 96. 102. 126.]
  [ 81.  75.  92.]]]
[[[239. 240. 246.]
  [239. 240. 247.]
  [239. 240. 247.]
  ...
  [170. 171. 175.]
  [172. 171. 175.]
  [170. 170. 173.]]

 [[237. 237. 247.]
  [237. 237. 246.]
  [238. 238. 246.]
  ...
  [170. 169. 175.]
  [171. 169. 175.]
  [168. 168. 174.]]

 [[237. 237. 246.]

[[[ 83.  96.  44.]
  [ 76.  87.  53.]
  [ 40.  51.  38.]
  ...
  [186. 197. 207.]
  [152. 167. 176.]
  [165. 177. 187.]]

 [[ 84.  95.  48.]
  [ 70.  80.  51.]
  [ 47.  58.  45.]
  ...
  [178. 186. 195.]
  [137. 149. 161.]
  [174. 185. 195.]]

 [[ 83.  92.  52.]
  [ 57.  67.  44.]
  [ 56.  62.  44.]
  ...
  [135. 139. 156.]
  [143. 155. 167.]
  [175. 186. 196.]]

 ...

 [[ 64.  74.  87.]
  [ 69.  79.  90.]
  [ 64.  75.  83.]
  ...
  [127. 134. 138.]
  [121. 128. 137.]
  [126. 133. 137.]]

 [[ 64.  75.  80.]
  [ 60.  70.  81.]
  [ 68.  79.  87.]
  ...
  [123. 130. 134.]
  [121. 128. 137.]
  [125. 132. 136.]]

 [[ 57.  63.  77.]
  [ 71.  82.  90.]
  [ 70.  81.  89.]
  ...
  [118. 129. 136.]
  [119. 130. 137.]
  [125. 132. 136.]]]
[[[ 95. 124.  68.]
  [ 82. 107.  50.]
  [ 95. 114.  58.]
  ...
  [128. 136. 125.]
  [145. 147. 133.]
  [143. 142. 124.]]

 [[ 91. 117.  69.]
  [ 89. 113.  61.]
  [ 86. 105.  49.]
  ...
  [139. 149. 138.]
  [150. 152. 138.]
  [149. 150. 132.]]

 [[ 77.  98.  55.]

[[[ 74.  70.  57.]
  [ 72.  69.  51.]
  [ 70.  70.  43.]
  ...
  [ 35.  23.   4.]
  [ 36.  24.  14.]
  [ 31.  19.   9.]]

 [[ 75.  70.  58.]
  [ 74.  71.  52.]
  [ 55.  55.  29.]
  ...
  [ 42.  30.  12.]
  [ 31.  20.   8.]
  [ 33.  22.  10.]]

 [[ 75.  71.  59.]
  [ 75.  72.  53.]
  [ 58.  58.  32.]
  ...
  [ 39.  27.   9.]
  [ 29.  18.   5.]
  [ 37.  26.  12.]]

 ...

 [[167. 140. 107.]
  [162. 134. 102.]
  [168. 141. 107.]
  ...
  [112.  79.  45.]
  [103.  70.  37.]
  [ 95.  62.  29.]]

 [[135. 109.  75.]
  [155. 128.  95.]
  [161. 134. 100.]
  ...
  [112.  79.  45.]
  [105.  71.  38.]
  [106.  73.  39.]]

 [[164. 137. 102.]
  [164. 137. 102.]
  [181. 154. 117.]
  ...
  [107.  74.  41.]
  [105.  70.  38.]
  [100.  65.  33.]]]
[[[247. 247. 247.]
  [247. 247. 247.]
  [248. 248. 248.]
  ...
  [249. 244. 239.]
  [249. 245. 240.]
  [249. 245. 240.]]

 [[247. 247. 247.]
  [247. 247. 247.]
  [248. 248. 248.]
  ...
  [250. 244. 238.]
  [250. 244. 238.]
  [250. 244. 238.]]

 [[247. 247. 247.]

[[[ 40.  47.  48.]
  [ 57.  61.  59.]
  [ 45.  50.  48.]
  ...
  [196. 201. 206.]
  [242. 246. 248.]
  [244. 245. 252.]]

 [[ 42.  48.  50.]
  [ 50.  53.  52.]
  [ 47.  50.  49.]
  ...
  [226. 230. 234.]
  [243. 244. 249.]
  [242. 246. 249.]]

 [[ 46.  50.  53.]
  [ 46.  49.  49.]
  [ 53.  56.  55.]
  ...
  [233. 236. 241.]
  [244. 245. 248.]
  [244. 245. 250.]]

 ...

 [[ 24.   6.   4.]
  [ 24.   6.   4.]
  [ 25.   6.   5.]
  ...
  [205. 201. 199.]
  [206. 202. 199.]
  [206. 202. 200.]]

 [[ 30.   5.   4.]
  [ 33.   8.   6.]
  [ 38.   8.   8.]
  ...
  [202. 199. 196.]
  [207. 203. 201.]
  [206. 203. 200.]]

 [[ 42.  11.  10.]
  [ 52.  16.  15.]
  [ 66.  17.  16.]
  ...
  [208. 204. 201.]
  [205. 201. 198.]
  [203. 199. 197.]]]
[[[ 54.  56.  68.]
  [126. 130. 148.]
  [130. 148. 167.]
  ...
  [138. 149. 181.]
  [136. 144. 170.]
  [141. 148. 168.]]

 [[ 84.  88. 102.]
  [ 66.  64.  84.]
  [134. 136. 157.]
  ...
  [133. 146. 172.]
  [136. 146. 169.]
  [138. 146. 168.]]

 [[ 87.  91. 108.]

[[[ 22.  23.  25.]
  [ 47.  48.  50.]
  [ 40.  41.  42.]
  ...
  [ 31.  41.  53.]
  [ 48.  61.  73.]
  [ 25.  27.  31.]]

 [[ 39.  36.  39.]
  [114. 111. 114.]
  [127. 123. 127.]
  ...
  [115. 139. 151.]
  [125. 152. 164.]
  [ 73.  74.  79.]]

 [[ 43.  38.  42.]
  [121. 116. 120.]
  [126. 122. 125.]
  ...
  [136. 160. 174.]
  [132. 157. 171.]
  [ 78.  79.  84.]]

 ...

 [[  0.   0.   0.]
  [  0.   0.   0.]
  [ 58.  58.  58.]
  ...
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]]

 [[  0.   0.   0.]
  [  0.   0.   0.]
  [ 83.  83.  83.]
  ...
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]]

 [[  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  ...
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]]]
[[[164. 168. 165.]
  [164. 168. 165.]
  [167. 171. 168.]
  ...
  [213. 207. 193.]
  [223. 217. 203.]
  [220. 214. 200.]]

 [[176. 180. 177.]
  [176. 180. 176.]
  [172. 176. 172.]
  ...
  [221. 216. 200.]
  [227. 221. 206.]
  [225. 219. 204.]]

 [[213. 217. 213.]

[[[197. 221. 205.]
  [146. 168. 153.]
  [140. 161. 146.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 [[ 85. 109.  93.]
  [ 95. 117. 102.]
  [101. 122. 107.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 [[ 81. 105.  89.]
  [111. 133. 118.]
  [102. 123. 108.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 ...

 [[ 90. 112. 110.]
  [ 92. 114. 112.]
  [ 88. 110. 108.]
  ...
  [144. 159. 136.]
  [134. 152. 128.]
  [131. 151. 126.]]

 [[ 93. 115. 113.]
  [ 94. 116. 114.]
  [ 94. 116. 114.]
  ...
  [124. 142. 118.]
  [133. 153. 128.]
  [130. 150. 125.]]

 [[ 92. 114. 112.]
  [ 93. 115. 113.]
  [ 95. 117. 115.]
  ...
  [131. 149. 125.]
  [138. 158. 133.]
  [125. 147. 122.]]]
[[[159. 202. 250.]
  [158. 203. 250.]
  [154. 202. 248.]
  ...
  [138. 169. 210.]
  [157. 190. 223.]
  [167. 194. 224.]]

 [[160. 202. 250.]
  [158. 203. 250.]
  [155. 202. 249.]
  ...
  [138. 164. 207.]
  [145. 172. 212.]
  [160. 181. 221.]]

 [[160. 203. 251.]

[[[220. 198. 180.]
  [220. 197. 179.]
  [188. 158. 150.]
  ...
  [240. 231. 253.]
  [239. 230. 253.]
  [239. 230. 253.]]

 [[220. 198. 179.]
  [219. 197. 178.]
  [206. 181. 168.]
  ...
  [240. 231. 253.]
  [239. 230. 254.]
  [239. 230. 254.]]

 [[217. 195. 177.]
  [215. 194. 175.]
  [205. 185. 168.]
  ...
  [240. 231. 254.]
  [240. 230. 253.]
  [239. 230. 253.]]

 ...

 [[ 25.  18.  17.]
  [ 25.  18.  17.]
  [ 26.  18.  18.]
  ...
  [  8.   9.   8.]
  [  8.   9.   8.]
  [  7.   9.   7.]]

 [[ 14.  13.  13.]
  [ 16.  13.  13.]
  [ 19.  13.  13.]
  ...
  [  6.   7.   5.]
  [  4.   6.   6.]
  [  7.   9.   9.]]

 [[ 10.  11.  11.]
  [  9.  11.  11.]
  [ 13.  10.   9.]
  ...
  [  8.   9.   7.]
  [  7.   9.   8.]
  [  9.  11.  11.]]]
[[[143. 150. 152.]
  [145. 149. 151.]
  [145. 151. 153.]
  ...
  [ 98.  17.  13.]
  [ 99.  18.  12.]
  [100.  18.  12.]]

 [[144. 147. 149.]
  [142. 149. 149.]
  [147. 150. 151.]
  ...
  [ 86.  15.  12.]
  [ 87.  15.   9.]
  [ 87.  15.   9.]]

 [[145. 148. 147.]

[[[ 61.  57.  46.]
  [ 92.  85.  77.]
  [ 70.  61.  56.]
  ...
  [ 96.  78.  64.]
  [ 90.  72.  58.]
  [ 91.  73.  59.]]

 [[ 93.  86.  76.]
  [ 70.  63.  53.]
  [ 92.  83.  76.]
  ...
  [ 90.  72.  58.]
  [ 85.  67.  53.]
  [ 93.  75.  61.]]

 [[102.  94.  83.]
  [ 72.  64.  53.]
  [ 66.  56.  47.]
  ...
  [ 92.  74.  60.]
  [ 97.  79.  65.]
  [103.  85.  71.]]

 ...

 [[ 54.  44.  35.]
  [ 45.  46.  41.]
  [ 41.  46.  50.]
  ...
  [ 76.  62.  61.]
  [ 84.  70.  69.]
  [ 81.  67.  66.]]

 [[ 39.  35.  32.]
  [ 38.  47.  46.]
  [ 25.  34.  41.]
  ...
  [ 76.  62.  61.]
  [ 82.  68.  67.]
  [ 80.  66.  65.]]

 [[ 42.  43.  45.]
  [ 32.  42.  44.]
  [ 49.  60.  66.]
  ...
  [ 80.  66.  65.]
  [ 86.  72.  71.]
  [ 89.  75.  74.]]]
[[[ 18.  18.  19.]
  [ 25.  25.  25.]
  [ 28.  29.  27.]
  ...
  [ 17.  12.  15.]
  [ 13.   9.  12.]
  [ 13.   9.  12.]]

 [[ 13.  14.  14.]
  [ 18.  18.  18.]
  [ 24.  24.  23.]
  ...
  [ 96.  87.  87.]
  [ 94.  85.  84.]
  [ 90.  81.  81.]]

 [[ 13.  14.  12.]

[[[ 15.  31.  24.]
  [  9.  27.  19.]
  [ 11.  26.  20.]
  ...
  [ 25.  47.  41.]
  [ 28.  49.  42.]
  [ 17.  35.  30.]]

 [[ 17.  34.  25.]
  [ 16.  33.  26.]
  [ 17.  32.  26.]
  ...
  [ 35.  58.  50.]
  [ 33.  55.  46.]
  [ 18.  40.  33.]]

 [[ 19.  35.  26.]
  [ 19.  35.  28.]
  [ 24.  39.  33.]
  ...
  [ 40.  62.  53.]
  [ 42.  66.  54.]
  [ 41.  62.  54.]]

 ...

 [[193. 193. 180.]
  [202. 201. 187.]
  [197. 197. 182.]
  ...
  [203. 205. 196.]
  [201. 202. 192.]
  [199. 200. 190.]]

 [[199. 199. 186.]
  [192. 192. 177.]
  [187. 187. 172.]
  ...
  [203. 205. 197.]
  [207. 209. 197.]
  [197. 197. 186.]]

 [[212. 210. 195.]
  [187. 186. 171.]
  [183. 184. 168.]
  ...
  [202. 203. 193.]
  [195. 197. 185.]
  [191. 193. 181.]]]
[[[255. 255. 228.]
  [251. 249. 224.]
  [255. 252. 243.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 [[255. 255. 228.]
  [250. 249. 223.]
  [254. 252. 243.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 [[255. 255. 228.]

[[[55. 65. 58.]
  [55. 64. 63.]
  [53. 63. 62.]
  ...
  [50. 58. 57.]
  [50. 58. 58.]
  [51. 56. 53.]]

 [[52. 60. 60.]
  [52. 61. 62.]
  [54. 63. 62.]
  ...
  [52. 58. 55.]
  [51. 58. 54.]
  [47. 56. 52.]]

 [[51. 58. 58.]
  [55. 60. 61.]
  [56. 63. 63.]
  ...
  [52. 57. 54.]
  [52. 57. 54.]
  [48. 56. 54.]]

 ...

 [[49. 51. 71.]
  [49. 51. 71.]
  [49. 51. 71.]
  ...
  [49. 51. 71.]
  [49. 51. 71.]
  [49. 51. 71.]]

 [[49. 51. 71.]
  [49. 51. 71.]
  [49. 51. 71.]
  ...
  [49. 51. 71.]
  [49. 51. 71.]
  [49. 51. 71.]]

 [[49. 51. 71.]
  [49. 51. 71.]
  [49. 51. 71.]
  ...
  [49. 51. 71.]
  [49. 51. 71.]
  [49. 51. 71.]]]
[[[242. 247. 251.]
  [168. 175. 183.]
  [147. 161. 172.]
  ...
  [101. 111. 120.]
  [ 89.  99. 108.]
  [ 94. 104. 113.]]

 [[249. 250. 252.]
  [230. 233. 238.]
  [188. 196. 206.]
  ...
  [ 99. 113. 124.]
  [ 83.  97. 108.]
  [ 88. 102. 113.]]

 [[251. 250. 248.]
  [254. 254. 255.]
  [245. 250. 254.]
  ...
  [ 99. 117. 131.]
  [ 82. 100. 114.]
  [ 92. 110. 124.]]

 ...

In [16]:
print(label_norm)

(0.18666666666666668, 0.6986666666666667, 0.396, 0.542)


In [17]:
X=np.array(data,dtype=np.float32)
y=np.array(output,dtype=np.float32)


x_train,x_test,y_train,y_test=train_test_split(X,y,train_size=0.8,random_state=0)
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((320, 224, 224, 3), (81, 224, 224, 3), (320, 4), (81, 4))

In [18]:
print(X.shape,y.shape)


(401, 224, 224, 3) (401, 4)


In [19]:
from tensorflow.keras.applications import MobileNetV2, InceptionV3, InceptionResNetV2
from tensorflow.keras.layers import Dense, Dropout, Flatten, Input
from tensorflow.keras.models import Model



In [20]:

inception_resnet= InceptionResNetV2(weights = "imagenet",include_top=False,input_tensor=Input(shape=(224,224,3)))
inception_resnet.trainable=False
headmodel = inception_resnet.output
headmodel=Flatten()(headmodel)
headmodel=Dense(500,activation="relu")(headmodel)
headmodel=Dense(250,activation="relu")(headmodel)
headmodel=Dense(4,activation='sigmoid')(headmodel)

In [21]:
model=Model(inputs=inception_resnet.input,outputs=headmodel)

In [22]:
import tensorflow as tf

In [23]:
#compile model
model.compile(loss='mse',optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4))
model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_1 (InputLayer)        [(None, 224, 224, 3)]        0         []                            
                                                                                                  
 conv2d (Conv2D)             (None, 111, 111, 32)         864       ['input_1[0][0]']             
                                                                                                  
 batch_normalization (Batch  (None, 111, 111, 32)         96        ['conv2d[0][0]']              
 Normalization)                                                                                   
                                                                                                  
 activation (Activation)     (None, 111, 111, 32)         0         ['batch_normalization[0][0

 conv2d_11 (Conv2D)          (None, 25, 25, 64)           12288     ['average_pooling2d[0][0]']   
                                                                                                  
 batch_normalization_5 (Bat  (None, 25, 25, 96)           288       ['conv2d_5[0][0]']            
 chNormalization)                                                                                 
                                                                                                  
 batch_normalization_7 (Bat  (None, 25, 25, 64)           192       ['conv2d_7[0][0]']            
 chNormalization)                                                                                 
                                                                                                  
 batch_normalization_10 (Ba  (None, 25, 25, 96)           288       ['conv2d_10[0][0]']           
 tchNormalization)                                                                                
          

 block35_1_conv (Conv2D)     (None, 25, 25, 320)          41280     ['block35_1_mixed[0][0]']     
                                                                                                  
 custom_scale_layer (Custom  (None, 25, 25, 320)          0         ['mixed_5b[0][0]',            
 ScaleLayer)                                                         'block35_1_conv[0][0]']      
                                                                                                  
 block35_1_ac (Activation)   (None, 25, 25, 320)          0         ['custom_scale_layer[0][0]']  
                                                                                                  
 conv2d_21 (Conv2D)          (None, 25, 25, 32)           10240     ['block35_1_ac[0][0]']        
                                                                                                  
 batch_normalization_21 (Ba  (None, 25, 25, 32)           96        ['conv2d_21[0][0]']           
 tchNormal

                                                                                                  
 activation_25 (Activation)  (None, 25, 25, 32)           0         ['batch_normalization_25[0][0]
                                                                    ']                            
                                                                                                  
 activation_28 (Activation)  (None, 25, 25, 48)           0         ['batch_normalization_28[0][0]
                                                                    ']                            
                                                                                                  
 conv2d_24 (Conv2D)          (None, 25, 25, 32)           10240     ['block35_2_ac[0][0]']        
                                                                                                  
 conv2d_26 (Conv2D)          (None, 25, 25, 32)           9216      ['activation_25[0][0]']       
          

                                                                                                  
 activation_32 (Activation)  (None, 25, 25, 32)           0         ['batch_normalization_32[0][0]
                                                                    ']                            
                                                                                                  
 activation_35 (Activation)  (None, 25, 25, 64)           0         ['batch_normalization_35[0][0]
                                                                    ']                            
                                                                                                  
 block35_4_mixed (Concatena  (None, 25, 25, 128)          0         ['activation_30[0][0]',       
 te)                                                                 'activation_32[0][0]',       
                                                                     'activation_35[0][0]']       
          

                                                                    ']                            
                                                                                                  
 conv2d_43 (Conv2D)          (None, 25, 25, 32)           10240     ['block35_5_ac[0][0]']        
                                                                                                  
 conv2d_46 (Conv2D)          (None, 25, 25, 48)           13824     ['activation_45[0][0]']       
                                                                                                  
 batch_normalization_43 (Ba  (None, 25, 25, 32)           96        ['conv2d_43[0][0]']           
 tchNormalization)                                                                                
                                                                                                  
 batch_normalization_46 (Ba  (None, 25, 25, 48)           144       ['conv2d_46[0][0]']           
 tchNormal

 batch_normalization_48 (Ba  (None, 25, 25, 32)           96        ['conv2d_48[0][0]']           
 tchNormalization)                                                                                
                                                                                                  
 batch_normalization_50 (Ba  (None, 25, 25, 32)           96        ['conv2d_50[0][0]']           
 tchNormalization)                                                                                
                                                                                                  
 batch_normalization_53 (Ba  (None, 25, 25, 64)           192       ['conv2d_53[0][0]']           
 tchNormalization)                                                                                
                                                                                                  
 activation_48 (Activation)  (None, 25, 25, 32)           0         ['batch_normalization_48[0][0]
          

 custom_scale_layer_7 (Cust  (None, 25, 25, 320)          0         ['block35_7_ac[0][0]',        
 omScaleLayer)                                                       'block35_8_conv[0][0]']      
                                                                                                  
 block35_8_ac (Activation)   (None, 25, 25, 320)          0         ['custom_scale_layer_7[0][0]']
                                                                                                  
 conv2d_63 (Conv2D)          (None, 25, 25, 32)           10240     ['block35_8_ac[0][0]']        
                                                                                                  
 batch_normalization_63 (Ba  (None, 25, 25, 32)           96        ['conv2d_63[0][0]']           
 tchNormalization)                                                                                
                                                                                                  
 activatio

                                                                    ']                            
                                                                                                  
 activation_70 (Activation)  (None, 25, 25, 48)           0         ['batch_normalization_70[0][0]
                                                                    ']                            
                                                                                                  
 conv2d_66 (Conv2D)          (None, 25, 25, 32)           10240     ['block35_9_ac[0][0]']        
                                                                                                  
 conv2d_68 (Conv2D)          (None, 25, 25, 32)           9216      ['activation_67[0][0]']       
                                                                                                  
 conv2d_71 (Conv2D)          (None, 25, 25, 64)           27648     ['activation_70[0][0]']       
          

                                                                                                  
 activation_77 (Activation)  (None, 12, 12, 128)          0         ['batch_normalization_77[0][0]
                                                                    ']                            
                                                                                                  
 conv2d_78 (Conv2D)          (None, 12, 12, 160)          143360    ['activation_77[0][0]']       
                                                                                                  
 batch_normalization_78 (Ba  (None, 12, 12, 160)          480       ['conv2d_78[0][0]']           
 tchNormalization)                                                                                
                                                                                                  
 activation_78 (Activation)  (None, 12, 12, 160)          0         ['batch_normalization_78[0][0]
          

                                                                                                  
 batch_normalization_85 (Ba  (None, 12, 12, 128)          384       ['conv2d_85[0][0]']           
 tchNormalization)                                                                                
                                                                                                  
 activation_85 (Activation)  (None, 12, 12, 128)          0         ['batch_normalization_85[0][0]
                                                                    ']                            
                                                                                                  
 conv2d_86 (Conv2D)          (None, 12, 12, 160)          143360    ['activation_85[0][0]']       
                                                                                                  
 batch_normalization_86 (Ba  (None, 12, 12, 160)          480       ['conv2d_86[0][0]']           
 tchNormal

                                                                    ]                             
                                                                                                  
 conv2d_93 (Conv2D)          (None, 12, 12, 128)          139264    ['block17_4_ac[0][0]']        
                                                                                                  
 batch_normalization_93 (Ba  (None, 12, 12, 128)          384       ['conv2d_93[0][0]']           
 tchNormalization)                                                                                
                                                                                                  
 activation_93 (Activation)  (None, 12, 12, 128)          0         ['batch_normalization_93[0][0]
                                                                    ']                            
                                                                                                  
 conv2d_94

 tomScaleLayer)                                                      'block17_6_conv[0][0]']      
                                                                                                  
 block17_6_ac (Activation)   (None, 12, 12, 1088)         0         ['custom_scale_layer_15[0][0]'
                                                                    ]                             
                                                                                                  
 conv2d_101 (Conv2D)         (None, 12, 12, 128)          139264    ['block17_6_ac[0][0]']        
                                                                                                  
 batch_normalization_101 (B  (None, 12, 12, 128)          384       ['conv2d_101[0][0]']          
 atchNormalization)                                                                               
                                                                                                  
 activatio

 block17_8_conv (Conv2D)     (None, 12, 12, 1088)         418880    ['block17_8_mixed[0][0]']     
                                                                                                  
 custom_scale_layer_17 (Cus  (None, 12, 12, 1088)         0         ['block17_7_ac[0][0]',        
 tomScaleLayer)                                                      'block17_8_conv[0][0]']      
                                                                                                  
 block17_8_ac (Activation)   (None, 12, 12, 1088)         0         ['custom_scale_layer_17[0][0]'
                                                                    ]                             
                                                                                                  
 conv2d_109 (Conv2D)         (None, 12, 12, 128)          139264    ['block17_8_ac[0][0]']        
                                                                                                  
 batch_nor

 block17_10_mixed (Concaten  (None, 12, 12, 384)          0         ['activation_112[0][0]',      
 ate)                                                                'activation_115[0][0]']      
                                                                                                  
 block17_10_conv (Conv2D)    (None, 12, 12, 1088)         418880    ['block17_10_mixed[0][0]']    
                                                                                                  
 custom_scale_layer_19 (Cus  (None, 12, 12, 1088)         0         ['block17_9_ac[0][0]',        
 tomScaleLayer)                                                      'block17_10_conv[0][0]']     
                                                                                                  
 block17_10_ac (Activation)  (None, 12, 12, 1088)         0         ['custom_scale_layer_19[0][0]'
                                                                    ]                             
          

 activation_123 (Activation  (None, 12, 12, 192)          0         ['batch_normalization_123[0][0
 )                                                                  ]']                           
                                                                                                  
 block17_12_mixed (Concaten  (None, 12, 12, 384)          0         ['activation_120[0][0]',      
 ate)                                                                'activation_123[0][0]']      
                                                                                                  
 block17_12_conv (Conv2D)    (None, 12, 12, 1088)         418880    ['block17_12_mixed[0][0]']    
                                                                                                  
 custom_scale_layer_21 (Cus  (None, 12, 12, 1088)         0         ['block17_11_ac[0][0]',       
 tomScaleLayer)                                                      'block17_12_conv[0][0]']     
          

 activation_128 (Activation  (None, 12, 12, 192)          0         ['batch_normalization_128[0][0
 )                                                                  ]']                           
                                                                                                  
 activation_131 (Activation  (None, 12, 12, 192)          0         ['batch_normalization_131[0][0
 )                                                                  ]']                           
                                                                                                  
 block17_14_mixed (Concaten  (None, 12, 12, 384)          0         ['activation_128[0][0]',      
 ate)                                                                'activation_131[0][0]']      
                                                                                                  
 block17_14_conv (Conv2D)    (None, 12, 12, 1088)         418880    ['block17_14_mixed[0][0]']    
          

 batch_normalization_139 (B  (None, 12, 12, 192)          576       ['conv2d_139[0][0]']          
 atchNormalization)                                                                               
                                                                                                  
 activation_136 (Activation  (None, 12, 12, 192)          0         ['batch_normalization_136[0][0
 )                                                                  ]']                           
                                                                                                  
 activation_139 (Activation  (None, 12, 12, 192)          0         ['batch_normalization_139[0][0
 )                                                                  ]']                           
                                                                                                  
 block17_16_mixed (Concaten  (None, 12, 12, 384)          0         ['activation_136[0][0]',      
 ate)     

 batch_normalization_144 (B  (None, 12, 12, 192)          576       ['conv2d_144[0][0]']          
 atchNormalization)                                                                               
                                                                                                  
 batch_normalization_147 (B  (None, 12, 12, 192)          576       ['conv2d_147[0][0]']          
 atchNormalization)                                                                               
                                                                                                  
 activation_144 (Activation  (None, 12, 12, 192)          0         ['batch_normalization_144[0][0
 )                                                                  ]']                           
                                                                                                  
 activation_147 (Activation  (None, 12, 12, 192)          0         ['batch_normalization_147[0][0
 )        

                                                                                                  
 conv2d_155 (Conv2D)         (None, 12, 12, 192)          215040    ['activation_154[0][0]']      
                                                                                                  
 batch_normalization_152 (B  (None, 12, 12, 192)          576       ['conv2d_152[0][0]']          
 atchNormalization)                                                                               
                                                                                                  
 batch_normalization_155 (B  (None, 12, 12, 192)          576       ['conv2d_155[0][0]']          
 atchNormalization)                                                                               
                                                                                                  
 activation_152 (Activation  (None, 12, 12, 192)          0         ['batch_normalization_152[0][0
 )        

 g2D)                                                                                             
                                                                                                  
 mixed_7a (Concatenate)      (None, 5, 5, 2080)           0         ['activation_157[0][0]',      
                                                                     'activation_159[0][0]',      
                                                                     'activation_162[0][0]',      
                                                                     'max_pooling2d_3[0][0]']     
                                                                                                  
 conv2d_164 (Conv2D)         (None, 5, 5, 192)            399360    ['mixed_7a[0][0]']            
                                                                                                  
 batch_normalization_164 (B  (None, 5, 5, 192)            576       ['conv2d_164[0][0]']          
 atchNorma

 e)                                                                  'activation_170[0][0]']      
                                                                                                  
 block8_2_conv (Conv2D)      (None, 5, 5, 2080)           933920    ['block8_2_mixed[0][0]']      
                                                                                                  
 custom_scale_layer_31 (Cus  (None, 5, 5, 2080)           0         ['block8_1_ac[0][0]',         
 tomScaleLayer)                                                      'block8_2_conv[0][0]']       
                                                                                                  
 block8_2_ac (Activation)    (None, 5, 5, 2080)           0         ['custom_scale_layer_31[0][0]'
                                                                    ]                             
                                                                                                  
 conv2d_17

 )                                                                  ]']                           
                                                                                                  
 block8_4_mixed (Concatenat  (None, 5, 5, 448)            0         ['activation_175[0][0]',      
 e)                                                                  'activation_178[0][0]']      
                                                                                                  
 block8_4_conv (Conv2D)      (None, 5, 5, 2080)           933920    ['block8_4_mixed[0][0]']      
                                                                                                  
 custom_scale_layer_33 (Cus  (None, 5, 5, 2080)           0         ['block8_3_ac[0][0]',         
 tomScaleLayer)                                                      'block8_4_conv[0][0]']       
                                                                                                  
 block8_4_

 )                                                                  ]']                           
                                                                                                  
 activation_186 (Activation  (None, 5, 5, 256)            0         ['batch_normalization_186[0][0
 )                                                                  ]']                           
                                                                                                  
 block8_6_mixed (Concatenat  (None, 5, 5, 448)            0         ['activation_183[0][0]',      
 e)                                                                  'activation_186[0][0]']      
                                                                                                  
 block8_6_conv (Conv2D)      (None, 5, 5, 2080)           933920    ['block8_6_mixed[0][0]']      
                                                                                                  
 custom_sc

 atchNormalization)                                                                               
                                                                                                  
 activation_191 (Activation  (None, 5, 5, 192)            0         ['batch_normalization_191[0][0
 )                                                                  ]']                           
                                                                                                  
 activation_194 (Activation  (None, 5, 5, 256)            0         ['batch_normalization_194[0][0
 )                                                                  ]']                           
                                                                                                  
 block8_8_mixed (Concatenat  (None, 5, 5, 448)            0         ['activation_191[0][0]',      
 e)                                                                  'activation_194[0][0]']      
          

 atchNormalization)                                                                               
                                                                                                  
 batch_normalization_202 (B  (None, 5, 5, 256)            768       ['conv2d_202[0][0]']          
 atchNormalization)                                                                               
                                                                                                  
 activation_199 (Activation  (None, 5, 5, 192)            0         ['batch_normalization_199[0][0
 )                                                                  ]']                           
                                                                                                  
 activation_202 (Activation  (None, 5, 5, 256)            0         ['batch_normalization_202[0][0
 )                                                                  ]']                           
          

In [24]:
pip install --upgrade tensorflow


Note: you may need to restart the kernel to use updated packages.Requirement already satisfied: tensorflow in c:\users\amrutha\anaconda3\lib\site-packages (2.15.0)
  Obtaining dependency information for tensorflow from https://files.pythonhosted.org/packages/ed/b6/62345568cd07de5d9254fcf64d7e44aacbb6abde11ea953b3cb320e58d19/tensorflow-2.17.0-cp311-cp311-win_amd64.whl.metadata
  Using cached tensorflow-2.17.0-cp311-cp311-win_amd64.whl.metadata (3.2 kB)
  Obtaining dependency information for tensorflow-intel==2.17.0 from https://files.pythonhosted.org/packages/66/03/5c447feceb72f5a38ac2aa79d306fa5b5772f982c2b480c1329c7e382900/tensorflow_intel-2.17.0-cp311-cp311-win_amd64.whl.metadata
  Using cached tensorflow_intel-2.17.0-cp311-cp311-win_amd64.whl.metadata (5.0 kB)
  Obtaining dependency information for flatbuffers>=24.3.25 from https://files.pythonhosted.org/packages/41/f0/7e988a019bc54b2dbd0ad4182ef2d53488bb02e58694cd79d61369e85900/flatbuffers-24.3.25-py2.py3-none-any.whl.metadata
  Us

ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\AMRUTHA\\anaconda3\\Lib\\site-packages\\~l_dtypes\\_custom_floats.cp311-win_amd64.pyd'
Consider using the `--user` option or check the permissions.



   - ------------------------------------- 16.1/385.0 MB 242.8 kB/s eta 0:25:20
   - ------------------------------------- 16.1/385.0 MB 243.2 kB/s eta 0:25:18
   - ------------------------------------- 16.1/385.0 MB 244.5 kB/s eta 0:25:09
   - ------------------------------------- 16.1/385.0 MB 244.5 kB/s eta 0:25:09
   - ------------------------------------- 16.2/385.0 MB 244.9 kB/s eta 0:25:07
   - ------------------------------------- 16.2/385.0 MB 244.9 kB/s eta 0:25:07
   - ------------------------------------- 16.2/385.0 MB 246.3 kB/s eta 0:24:58
   - ------------------------------------- 16.2/385.0 MB 246.4 kB/s eta 0:24:57
   - ------------------------------------- 16.2/385.0 MB 246.8 kB/s eta 0:24:55
   - ------------------------------------- 16.3/385.0 MB 247.8 kB/s eta 0:24:49
   - ------------------------------------- 16.3/385.0 MB 248.2 kB/s eta 0:24:46
   - ------------------------------------- 16.3/385.0 MB 248.7 kB/s eta 0:24:43
   - -----------------------------------

In [25]:
from tensorflow.keras.callbacks import TensorBoard
tfb = TensorBoard(log_dir='object_detection')


In [26]:
from tensorflow.keras.callbacks import TensorBoard
tfb=TensorBoard('object_detection')

In [27]:
history=model.fit(x=x_train,y=y_train,batch_size=10,epochs=100,validation_data=(x_test,y_test),callbacks=[tfb])

Epoch 1/100

32/32 [==============================] - 199s 5s/step - loss: 0.1092 - val_loss: 0.1074
Epoch 2/100
32/32 [==============================] - 40s 1s/step - loss: 0.0998 - val_loss: 0.1094
Epoch 3/100
32/32 [==============================] - 41s 1s/step - loss: 0.0906 - val_loss: 0.0942
Epoch 4/100
32/32 [==============================] - 45s 1s/step - loss: 0.0847 - val_loss: 0.0898
Epoch 5/100
32/32 [==============================] - 45s 1s/step - loss: 0.0821 - val_loss: 0.0898
Epoch 6/100
32/32 [==============================] - 45s 1s/step - loss: 0.0805 - val_loss: 0.0894
Epoch 7/100
32/32 [==============================] - 45s 1s/step - loss: 0.0795 - val_loss: 0.0892
Epoch 8/100
32/32 [==============================] - 47s 1s/step - loss: 0.0781 - val_loss: 0.0883
Epoch 9/100
32/32 [==============================] - 46s 1s/step - loss: 0.0777 - val_loss: 0.0889
Epoch 10/100
32/32 [==============================] - 50s 2s/step - loss: 0.0769 - val_loss: 0.0865
Epoch 1

Epoch 79/100
32/32 [==============================] - 38s 1s/step - loss: 8.8731e-04 - val_loss: 0.0150
Epoch 80/100
32/32 [==============================] - 39s 1s/step - loss: 9.4907e-04 - val_loss: 0.0143
Epoch 81/100
32/32 [==============================] - 40s 1s/step - loss: 0.0011 - val_loss: 0.0153
Epoch 82/100
32/32 [==============================] - 42s 1s/step - loss: 9.6048e-04 - val_loss: 0.0150
Epoch 83/100
32/32 [==============================] - 43s 1s/step - loss: 7.4623e-04 - val_loss: 0.0151
Epoch 84/100
32/32 [==============================] - 42s 1s/step - loss: 7.3185e-04 - val_loss: 0.0145
Epoch 85/100
32/32 [==============================] - 43s 1s/step - loss: 6.4027e-04 - val_loss: 0.0144
Epoch 86/100
32/32 [==============================] - 42s 1s/step - loss: 5.2595e-04 - val_loss: 0.0149
Epoch 87/100
32/32 [==============================] - 42s 1s/step - loss: 4.6585e-04 - val_loss: 0.0143
Epoch 88/100
32/32 [==============================] - 44s 1s/step - 

In [28]:
history=model.fit(x=x_train,y=y_train,batch_size=10,epochs=200,validation_data=(x_test,y_test),callbacks=[tfb],initial_epoch=100)

Epoch 101/200
32/32 [==============================] - 42s 1s/step - loss: 5.7350e-04 - val_loss: 0.0146
Epoch 102/200
32/32 [==============================] - 42s 1s/step - loss: 6.0740e-04 - val_loss: 0.0144
Epoch 103/200
32/32 [==============================] - 42s 1s/step - loss: 5.8910e-04 - val_loss: 0.0150
Epoch 104/200
32/32 [==============================] - 45s 1s/step - loss: 6.4269e-04 - val_loss: 0.0142
Epoch 105/200
32/32 [==============================] - 45s 1s/step - loss: 6.2241e-04 - val_loss: 0.0151
Epoch 106/200
32/32 [==============================] - 41s 1s/step - loss: 4.7601e-04 - val_loss: 0.0144
Epoch 107/200
32/32 [==============================] - 41s 1s/step - loss: 4.3376e-04 - val_loss: 0.0144
Epoch 108/200
32/32 [==============================] - 40s 1s/step - loss: 4.0070e-04 - val_loss: 0.0149
Epoch 109/200
32/32 [==============================] - 40s 1s/step - loss: 4.3878e-04 - val_loss: 0.0145
Epoch 110/200
32/32 [==============================] - 

Epoch 179/200
32/32 [==============================] - 65s 2s/step - loss: 5.4995e-04 - val_loss: 0.0146
Epoch 180/200
32/32 [==============================] - 65s 2s/step - loss: 4.6821e-04 - val_loss: 0.0144
Epoch 181/200
32/32 [==============================] - 65s 2s/step - loss: 4.9449e-04 - val_loss: 0.0135
Epoch 182/200
32/32 [==============================] - 65s 2s/step - loss: 4.9779e-04 - val_loss: 0.0155
Epoch 183/200
32/32 [==============================] - 65s 2s/step - loss: 4.5777e-04 - val_loss: 0.0149
Epoch 184/200
32/32 [==============================] - 66s 2s/step - loss: 4.7721e-04 - val_loss: 0.0145
Epoch 185/200
32/32 [==============================] - 65s 2s/step - loss: 4.6248e-04 - val_loss: 0.0146
Epoch 186/200
32/32 [==============================] - 70s 2s/step - loss: 5.1032e-04 - val_loss: 0.0144
Epoch 187/200
32/32 [==============================] - 95s 3s/step - loss: 4.2951e-04 - val_loss: 0.0142
Epoch 188/200
32/32 [==============================] - 

In [29]:
 len(image_path)

401

In [30]:
X.shape

(401, 224, 224, 3)

In [31]:
y.shape

(401, 4)

In [32]:
model.save('./models/object_detection.h5')

C:\Users\AMRUTHA\anaconda3\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
